# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "utm/windows-11"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 300
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm"
  
  config.vm.provider "utm" do |u|
    u.cpus = 2
    u.memory = 4096
    # We do not have a QEMU guest agent for Windows ARM
    u.check_guest_additions = false
  end
end